import { CanteenFood } from '@/types/nutribot';

export const CANTEEN_MENU: CanteenFood[] = [
  { name: "Masala Dosa", category: "South Indian", unit: "piece", calories: 250, protein: 5, carbs: 35, fat: 10, isVeg: true },
  { name: "Idli", category: "South Indian", unit: "piece", calories: 60, protein: 2, carbs: 12, fat: 0.5, isVeg: true },
  { name: "Vada", category: "South Indian", unit: "piece", calories: 130, protein: 4, carbs: 15, fat: 7, isVeg: true },
  { name: "Upma", category: "South Indian", unit: "plate", calories: 200, protein: 5, carbs: 30, fat: 7, isVeg: true },
  { name: "Poha", category: "Breakfast", unit: "plate", calories: 180, protein: 4, carbs: 32, fat: 5, isVeg: true },
  { name: "Aloo Paratha", category: "Paratha", unit: "piece", calories: 300, protein: 6, carbs: 40, fat: 12, isVeg: true },
  { name: "Paneer Paratha", category: "Paratha", unit: "piece", calories: 350, protein: 12, carbs: 38, fat: 16, isVeg: true },
  { name: "Plain Paratha", category: "Paratha", unit: "piece", calories: 220, protein: 5, carbs: 30, fat: 9, isVeg: true },
  { name: "Chole Bhature", category: "Punjabi", unit: "plate", calories: 550, protein: 15, carbs: 65, fat: 25, isVeg: true },
  { name: "Rajma Rice", category: "Punjabi", unit: "plate", calories: 450, protein: 14, carbs: 70, fat: 10, isVeg: true },
  { name: "Dal Rice", category: "Thali", unit: "plate", calories: 380, protein: 12, carbs: 60, fat: 8, isVeg: true },
  { name: "Veg Thali", category: "Thali", unit: "plate", calories: 650, protein: 18, carbs: 85, fat: 22, isVeg: true },
  { name: "Paneer Butter Masala", category: "Paneer", unit: "plate", calories: 400, protein: 15, carbs: 20, fat: 28, isVeg: true },
  { name: "Shahi Paneer", category: "Paneer", unit: "plate", calories: 380, protein: 14, carbs: 18, fat: 26, isVeg: true },
  { name: "Palak Paneer", category: "Paneer", unit: "plate", calories: 320, protein: 16, carbs: 15, fat: 22, isVeg: true },
  { name: "Veg Biryani", category: "Biryani", unit: "plate", calories: 420, protein: 10, carbs: 60, fat: 14, isVeg: true },
  { name: "Chicken Biryani", category: "Biryani", unit: "plate", calories: 550, protein: 28, carbs: 55, fat: 22, isVeg: false },
  { name: "Egg Biryani", category: "Biryani", unit: "plate", calories: 480, protein: 18, carbs: 55, fat: 18, isVeg: false },
  { name: "Fried Rice", category: "Chinese", unit: "plate", calories: 350, protein: 8, carbs: 50, fat: 12, isVeg: true },
  { name: "Veg Noodles", category: "Chinese", unit: "plate", calories: 380, protein: 9, carbs: 55, fat: 14, isVeg: true },
  { name: "Manchurian", category: "Chinese", unit: "plate", calories: 280, protein: 6, carbs: 35, fat: 12, isVeg: true },
  { name: "Spring Roll", category: "Chinese", unit: "piece", calories: 120, protein: 3, carbs: 15, fat: 5, isVeg: true },
  { name: "Samosa", category: "Snacks", unit: "piece", calories: 150, protein: 3, carbs: 18, fat: 8, isVeg: true },
  { name: "Kachori", category: "Snacks", unit: "piece", calories: 180, protein: 4, carbs: 22, fat: 9, isVeg: true },
  { name: "Pav Bhaji", category: "Snacks", unit: "plate", calories: 400, protein: 10, carbs: 55, fat: 15, isVeg: true },
  { name: "Vada Pav", category: "Snacks", unit: "piece", calories: 280, protein: 6, carbs: 35, fat: 12, isVeg: true },
  { name: "Pani Puri", category: "Chaat", unit: "plate", calories: 200, protein: 4, carbs: 35, fat: 5, isVeg: true },
  { name: "Bhel Puri", category: "Chaat", unit: "plate", calories: 180, protein: 4, carbs: 30, fat: 5, isVeg: true },
  { name: "Sev Puri", category: "Chaat", unit: "plate", calories: 220, protein: 5, carbs: 32, fat: 8, isVeg: true },
  { name: "Dahi Puri", category: "Chaat", unit: "plate", calories: 250, protein: 6, carbs: 35, fat: 9, isVeg: true },
  { name: "Sandwich", category: "Sandwich", unit: "piece", calories: 250, protein: 8, carbs: 30, fat: 10, isVeg: true },
  { name: "Grilled Sandwich", category: "Sandwich", unit: "piece", calories: 300, protein: 10, carbs: 32, fat: 14, isVeg: true },
  { name: "Cheese Sandwich", category: "Sandwich", unit: "piece", calories: 350, protein: 12, carbs: 30, fat: 18, isVeg: true },
  { name: "Egg Sandwich", category: "Sandwich", unit: "piece", calories: 280, protein: 14, carbs: 28, fat: 12, isVeg: false },
  { name: "Omelette", category: "Egg", unit: "piece", calories: 180, protein: 12, carbs: 2, fat: 14, isVeg: false },
  { name: "Boiled Egg", category: "Egg", unit: "piece", calories: 80, protein: 6, carbs: 1, fat: 5, isVeg: false },
  { name: "Egg Bhurji", category: "Egg", unit: "plate", calories: 220, protein: 14, carbs: 5, fat: 16, isVeg: false },
  { name: "Tea", category: "Beverages", unit: "cup", calories: 50, protein: 1, carbs: 8, fat: 1, isVeg: true },
  { name: "Coffee", category: "Beverages", unit: "cup", calories: 60, protein: 1, carbs: 10, fat: 2, isVeg: true },
  { name: "Lassi", category: "Beverages", unit: "glass", calories: 180, protein: 5, carbs: 25, fat: 6, isVeg: true },
  { name: "Mango Shake", category: "Beverages", unit: "glass", calories: 220, protein: 4, carbs: 40, fat: 5, isVeg: true },
  { name: "Banana Shake", category: "Beverages", unit: "glass", calories: 200, protein: 5, carbs: 35, fat: 5, isVeg: true },
  { name: "Cold Coffee", category: "Beverages", unit: "glass", calories: 180, protein: 4, carbs: 28, fat: 6, isVeg: true },
  { name: "Lemon Juice", category: "Beverages", unit: "glass", calories: 60, protein: 0, carbs: 15, fat: 0, isVeg: true },
  { name: "Gulab Jamun", category: "Sweet", unit: "piece", calories: 150, protein: 2, carbs: 25, fat: 5, isVeg: true },
  { name: "Rasgulla", category: "Sweet", unit: "piece", calories: 120, protein: 2, carbs: 22, fat: 3, isVeg: true },
  { name: "Kheer", category: "Sweet", unit: "bowl", calories: 200, protein: 5, carbs: 35, fat: 6, isVeg: true },
  { name: "Ice Cream", category: "Sweet", unit: "scoop", calories: 140, protein: 2, carbs: 18, fat: 7, isVeg: true },
  { name: "Maggi", category: "Maggie", unit: "plate", calories: 320, protein: 8, carbs: 45, fat: 12, isVeg: true },
  { name: "Roti", category: "Bread", unit: "piece", calories: 80, protein: 3, carbs: 15, fat: 1, isVeg: true },
  { name: "Naan", category: "Bread", unit: "piece", calories: 150, protein: 4, carbs: 28, fat: 3, isVeg: true },
  { name: "Butter Naan", category: "Bread", unit: "piece", calories: 200, protein: 4, carbs: 28, fat: 8, isVeg: true },
  { name: "Plain Rice", category: "Rice", unit: "plate", calories: 200, protein: 4, carbs: 45, fat: 0.5, isVeg: true },
  { name: "Jeera Rice", category: "Rice", unit: "plate", calories: 220, protein: 4, carbs: 45, fat: 3, isVeg: true },
];

export const ACTIVITY_LEVEL_LABELS: Record<string, string> = {
  sedentary: 'Sedentary (little or no exercise)',
  light: 'Light (exercise 1-3 days/week)',
  moderate: 'Moderate (exercise 3-5 days/week)',
  active: 'Active (exercise 6-7 days/week)',
  very_active: 'Very Active (intense exercise daily)'
};

export const GOAL_LABELS: Record<string, string> = {
  lose: 'Lose Weight',
  maintain: 'Maintain Weight',
  gain: 'Gain Weight'
};
