import { db } from '@/db';
import { menuItems } from '@/db/schema';
import { eq } from 'drizzle-orm';

async function main() {
    const sampleMenuItems = [
        // Hot Beverages
        {
            name: 'Masala Tea',
            category: 'Hot Beverages',
            price: 15,
            description: 'Aromatic Indian tea with fresh spices and herbs',
            imageUrl: 'https://images.unsplash.com/photo-1594631252845-29fc4586c55c?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },
        {
            name: 'Filter Coffee',
            category: 'Hot Beverages',
            price: 15,
            description: 'Strong South Indian filter coffee with milk',
            imageUrl: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },
        {
            name: 'Green Tea',
            category: 'Hot Beverages',
            price: 20,
            description: 'Refreshing green tea with antioxidants',
            imageUrl: 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },
        {
            name: 'Hot Chocolate',
            category: 'Hot Beverages',
            price: 30,
            description: 'Rich and creamy hot chocolate drink',
            imageUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 7,
        },
        {
            name: 'Lemon Tea',
            category: 'Hot Beverages',
            price: 10,
            description: 'Refreshing tea with a hint of lemon',
            imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },

        // Cold Beverages
        {
            name: 'Cold Coffee',
            category: 'Cold Beverages',
            price: 35,
            description: 'Chilled coffee with milk and ice cream',
            imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 7,
        },
        {
            name: 'Sweet Lassi',
            category: 'Cold Beverages',
            price: 30,
            description: 'Traditional yogurt-based sweet drink',
            imageUrl: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },
        {
            name: 'Fresh Lime Soda',
            category: 'Cold Beverages',
            price: 25,
            description: 'Refreshing lime soda with fresh lemon',
            imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },
        {
            name: 'Mango Shake',
            category: 'Cold Beverages',
            price: 40,
            description: 'A luscious, creamy blend of sun-ripened Alphonso mangoes and chilled milk, topped with a swirl of fresh cream and garnished with chopped nuts. A refreshing tropical treat that\'s like summer in a glass.',
            imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2ad299dd4?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 7,
        },
        {
            name: 'Chocolate Shake',
            category: 'Cold Beverages',
            price: 45,
            description: 'Rich chocolate shake with ice cream',
            imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 7,
        },

        // South Indian Snacks
        {
            name: 'Idli (2 pcs)',
            category: 'South Indian Snacks',
            price: 30,
            description: 'Soft steamed rice cakes served with sambar and chutney',
            imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 10,
        },
        {
            name: 'Masala Dosa',
            category: 'South Indian Snacks',
            price: 40,
            description: 'Crispy rice crepe filled with spiced potato',
            imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Medu Vada (2 pcs)',
            category: 'South Indian Snacks',
            price: 30,
            description: 'Crispy lentil donuts served with sambar and chutney',
            imageUrl: 'https://images.unsplash.com/photo-1626500155537-4d6d63428905?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },
        {
            name: 'Onion Uttapam',
            category: 'South Indian Snacks',
            price: 50,
            description: 'Thick rice pancake topped with onions and spices',
            imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },

        // Maharashtrian Snacks
        {
            name: 'Vada Pav',
            category: 'Maharashtrian Snacks',
            price: 20,
            description: 'Mumbai style spiced potato fritter in a bun',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767796552094.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 10,
        },
        {
            name: 'Misal Pav',
            category: 'Maharashtrian Snacks',
            price: 40,
            description: 'Spicy sprouted lentils curry with bread',
            imageUrl: 'https://images.unsplash.com/photo-1601050634129-07510499eaf2?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Pav Bhaji',
            category: 'Maharashtrian Snacks',
            price: 50,
            description: 'Spiced mixed vegetable curry with buttered bread',
            imageUrl: 'https://images.unsplash.com/photo-1626132646529-500637532537?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },

        // Bhel/Chaat
        {
            name: 'Ragda Pattice',
            category: 'Bhel/Chaat',
            price: 45,
            description: 'Crispy potato patties served with a spicy white pea gravy (ragda), topped with tangy chutneys, finely chopped onions, and crunchy sev. A Mumbai street food classic.',
            imageUrl: 'https://images.unsplash.com/photo-1626132646529-500637532537?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },
        {
            name: 'Pani Puri',
            category: 'Bhel/Chaat',
            price: 35,
            description: 'Crispy hollow puris filled with a spicy mixture of potatoes and chickpeas, served with a tangy, refreshing mint and tamarind water. An explosion of flavors in every bite.',
            imageUrl: 'https://images.unsplash.com/photo-1601050634129-07510499eaf2?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },

        // Paratha
        {
            name: 'Aloo Paratha',
            category: 'Paratha',
            price: 40,
            description: 'Whole wheat flatbread stuffed with spiced potatoes',
            imageUrl: 'https://images.unsplash.com/photo-1606491956391-70868b5d0f47?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Paneer Paratha',
            category: 'Paratha',
            price: 60,
            description: 'Flatbread stuffed with cottage cheese and spices',
            imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c17360?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },

        // Special Snacks
        {
            name: 'Samosa (2 pcs)',
            category: 'Special Snacks',
            price: 15,
            description: 'Crispy triangular pastry with spiced potato filling',
            imageUrl: 'https://images.unsplash.com/photo-1601050634129-07510499eaf2?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 10,
        },
        {
            name: 'Bread Pakora',
            category: 'Special Snacks',
            price: 25,
            description: 'Bread slices dipped in spiced batter and deep fried',
            imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },

        // Maggie
        {
            name: 'Plain Maggi',
            category: 'Maggie',
            price: 30,
            description: 'Classic instant noodles',
            imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 7,
        },
        {
            name: 'Veg Maggi',
            category: 'Maggie',
            price: 40,
            description: 'Instant noodles with mixed vegetables',
            imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },

        // Sandwiches/Toast
        {
            name: 'Veg Sandwich',
            category: 'Sandwiches/Toast',
            price: 35,
            description: 'Fresh vegetable sandwich with chutney',
            imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 10,
        },
        {
            name: 'Grilled Sandwich',
            category: 'Sandwiches/Toast',
            price: 50,
            description: 'Crispy grilled sandwich with vegetables and cheese',
            imageUrl: 'https://images.unsplash.com/photo-1539252554454-31d626304679?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },

        // Rolls
        {
            name: 'Veg Roll',
            category: 'Rolls',
            price: 50,
            description: 'Rolled flatbread with mixed vegetables',
            imageUrl: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Paneer Roll',
            category: 'Rolls',
            price: 70,
            description: 'Rolled flatbread with spiced cottage cheese',
            imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },

        // Chinese Starter
        {
            name: 'Veg Manchurian',
            category: 'Chinese Starter',
            price: 110,
            description: 'Crispy vegetable balls tossed in a tangy, spicy, and savory Manchurian sauce, garnished with fresh spring onions.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767980181699.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 20,
        },
        {
            name: 'Paneer Chilli',
            category: 'Chinese Starter',
            price: 130,
            description: 'Cubes of tender paneer wok-tossed in a spicy and tangy Indo-Chinese sauce with crisp bell peppers, onions, and fresh green chillies.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767980140831.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Spring Roll (4 pcs)',
            category: 'Chinese Starter',
            price: 70,
            description: 'Deliciously crispy golden-brown rolls filled with a savory mix of finely shredded seasonal vegetables and aromatic spices. Served with a tangy dipping sauce.',
            imageUrl: 'https://images.unsplash.com/photo-1544333346-64e4fe18204b?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },

        {
            name: 'Paneer Noodles',
            category: 'Chinese Noodles/Rice',
            price: 90,
            description: 'Soft, golden-fried paneer cubes tossed with wok-seared noodles, crisp seasonal vegetables, and a signature blend of aromatic Indo-Chinese spices and savory sauces. A delightful fusion of textures and flavors.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767977767801.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Schezwan Noodles',
            category: 'Chinese Noodles/Rice',
            price: 95,
            description: 'Fiery wok-tossed noodles with crisp vegetables and a bold Schezwan sauce, packing a punch of heat and garlic. A spicy Indo-Chinese favorite.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767977946687.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Egg Curry with Rice',
            category: 'Special Dishes',
            price: 85,
            description: 'A soul-warming comfort meal featuring two perfectly boiled eggs simmered in a rich, spicy tomato-onion gravy, served alongside a generous portion of fluffy, aromatic steamed Basmati rice.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978383746.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: false,
            preparationTime: 20,
        },
        {
            name: 'Chole with Kulcha',
            category: 'Punjabi Dishes',
            price: 70,
            description: 'Spicy chickpeas with soft flatbread',
            imageUrl: 'https://images.unsplash.com/photo-1596797038583-18a68a637311?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Dabeli Special',
            category: 'Special Dishes',
            price: 30,
            description: 'Special Kutchi dabeli with extra toppings',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767803335262.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 10,
        },
        {
            name: 'Kadhi Pakora',
            category: 'Special Dishes',
            price: 85,
            description: 'Golden gram flour fritters (pakoras) submerged in a tangy and creamy yogurt-based gravy tempered with aromatic spices. Best enjoyed with steamed rice.',
            imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 20,
        },

        // Punjabi Dishes
        {
            name: 'Dal Makhani',
            category: 'Punjabi Dishes',
            price: 110,
            description: 'A rich, creamy, and slow-cooked masterpiece of black lentils and kidney beans, simmered overnight with butter, cream, and a signature blend of spices. This ultimate North Indian comfort food is velvety smooth and packed with deep, smoky flavors.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767980815162.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },
        {
            name: 'Aloo Gobi',
            category: 'Punjabi Dishes',
            price: 75,
            description: 'A classic vegetarian stir-fry of tender cauliflower florets and potatoes, seasoned with turmeric, ginger, and a blend of traditional Indian spices.',
            imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },

        // Paneer Dishes
        {
            name: 'Paneer Butter Masala',
            category: 'Paneer Dishes',
            price: 120,
            description: 'Cottage cheese in rich tomato and butter gravy',
            imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },
        {
            name: 'Paneer Tikka Masala',
            category: 'Paneer Dishes',
            price: 145,
            description: 'Succulent cubes of marinated paneer grilled to perfection and simmered in a rich, creamy, and mildly spiced tomato-based gravy. A luxurious North Indian classic.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978345964.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },
        {
            name: 'Kadai Paneer',
            category: 'Paneer Dishes',
            price: 135,
            description: 'Fresh paneer cubes tossed with bell peppers, onions, and tomatoes in a spicy, freshly ground kadai masala. Bold flavors with a rustic touch.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978370110.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 20,
        },
        {
            name: 'Palak Paneer',
            category: 'Paneer Dishes',
            price: 130,
            description: 'Soft cottage cheese cubes in a smooth, vibrant spinach gravy, tempered with garlic, cumin, and finished with a touch of cream.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978403360.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 20,
        },
        {
            name: 'Shahi Paneer',
            category: 'Paneer Dishes',
            price: 150,
            description: 'A royal preparation of paneer in a silky, white gravy made from cashew paste, cream, and aromatic spices. Elegantly sweet and savory.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978447772.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },

        // Non-Veg
        {
            name: 'Chicken Biryani',
            category: 'Non-Veg Indian Dishes',
            price: 150,
            description: 'An exquisite culinary masterpiece featuring tender, succulent chicken pieces marinated in a secret royal spice blend, slow-cooked to perfection with layers of aged, long-grain Basmati rice in the traditional Dum Pukht style. Infused with saffron and garnished with caramelized onions and fresh mint for a truly regal experience.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978689240.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: false,
            preparationTime: 30,
        },
        {
            name: 'Chicken Tikka',
            category: 'Non-Veg Indian Dishes',
            price: 160,
            description: 'Succulent pieces of boneless chicken marinated in a robust blend of yogurt and hand-ground spices, then chargrilled to perfection in a traditional clay oven. Served with refreshing mint chutney and pickled onions.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978286180.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: false,
            preparationTime: 20,
        },
        {
            name: 'Butter Chicken with Naan',
            category: 'Non-Veg Indian Dishes',
            price: 180,
            description: 'A quintessential Indian favorite featuring succulent pieces of tandoori-grilled chicken simmered in a velvet-smooth, buttery tomato gravy with aromatic spices. Served with two pieces of soft, garlic-infused butter naan for a complete, indulgent meal.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978451333.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: false,
            preparationTime: 25,
        },

        // Rice
        {
            name: 'Veg Pulao',
            category: 'Rice',
            price: 95,
            description: 'A fragrant and flavorful rice dish cooked with long-grain Basmati rice, garden-fresh vegetables, and a blend of aromatic whole spices. Served with a side of cooling raita and sliced onions.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978744337.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 20,
        },
        {
            name: 'Jeera Rice',
            category: 'Rice',
            price: 65,
            description: 'Fragrant Basmati rice tempered with cumin seeds and aromatic whole spices, garnished with fresh coriander. A perfect flavorful alternative to plain rice.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767978676039.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 12,
        },
        {
            name: 'Rajma Rice',
            category: 'Rice',
            price: 90,
            description: 'Hearty red kidney beans simmered in a thick, spicy tomato-onion gravy, served with perfectly steamed long-grain Basmati rice. The ultimate comfort food.',
            imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 15,
        },
        {
            name: 'Plain Rice',
            category: 'Rice',
            price: 50,
            description: 'Perfectly steamed, fluffy long-grain Basmati rice. The ideal accompaniment to any curry or dal.',
            imageUrl: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 10,
        },

        // Sweet
        {
            name: 'Gulab Jamun (2 pcs)',
            category: 'Sweet',
            price: 30,
            description: 'Soft milk dumplings in sugar syrup',
            imageUrl: 'https://images.unsplash.com/photo-1589119908995-c6837fa14848?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 5,
        },

        // Thali
        {
            name: 'Veg Thali',
            category: 'Thali',
            price: 110,
            description: 'Complete meal with dal, sabzi, roti, rice, and sweet',
            imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=1000&auto=format&fit=crop',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },
        // Biryani
        {
            name: 'Veg Biryani',
            category: 'Biryani',
            price: 100,
            description: 'Fragrant rice with mixed vegetables and spices',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767980288410.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },
        {
            name: 'Paneer Biryani',
            category: 'Biryani',
            price: 130,
            description: 'Fragrant Basmati rice cooked with succulent paneer cubes, aromatic spices, and garden-fresh vegetables. A vegetarian delight.',
            imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/project-uploads/afcbb218-2c8c-4be5-9ba5-b03880bd1f88/image-1767980320602.png?width=8000&height=8000&resize=contain',
            isAvailable: true,
            isVeg: true,
            preparationTime: 25,
        },
    ];

    console.log('🔄 Updating/Adding menu items...');

    for (const item of sampleMenuItems) {
        // Try to update first
        const existing = await db.select().from(menuItems).where(eq(menuItems.name, item.name)).limit(1);
        
        if (existing.length > 0) {
            await db.update(menuItems)
                .set({ 
                    imageUrl: item.imageUrl,
                    description: item.description,
                    price: item.price,
                    category: item.category,
                    isAvailable: item.isAvailable,
                    isVeg: item.isVeg,
                    preparationTime: item.preparationTime
                })
                .where(eq(menuItems.name, item.name));
            console.log(`✅ Updated: ${item.name}`);
        } else {
            await db.insert(menuItems).values({
                ...item,
                createdAt: new Date().toISOString(),
            });
            console.log(`✅ Inserted: ${item.name}`);
        }
    }
    
    console.log('✨ Menu sync completed!');
}

main().catch((error) => {
    console.error('❌ Sync failed:', error);
});
